from graphviz import Digraph

dot = Digraph(comment='The Round Table')
dot.node('1', 'wannacry.exe')
dot.node('2', 'cmd.exe')
dot.node('3', '!wannadecryptor.exe')
dot.node('4', 'taskkill.exe')
dot.node('5', 'taskkill.exe')
dot.node('6', 'taskkill.exe')
dot.node('7', 'taskkill.exe')
dot.node('8', '!wannadecryptor.exe')
dot.node('9', 'cmd.exe')
dot.node('10', '!wannadecryptor.exe')
dot.node('11', 'cscript.exe')
dot.node('12', '!wannadecryptor.exe')

dot.edge('1', '2')
dot.edge('1', '3')
dot.edge('1', '4')
dot.edge('1', '5')
dot.edge('1', '6')
dot.edge('1', '7')
dot.edge('1', '8')
dot.edge('1', '9')
dot.edge('1', '10')
dot.edge('2', '11')
dot.edge('9', '12')

print(dot.source)  
dot.render('public/round-table.gv', format='svg', view=True)  
